### ISSUE TITLE
New prompt doesn't work when running as root

### ISSUE THREAD

**Issue by mrgilman** [thoughtbot/dotfiles#270]
I was experimenting with some unix stuff today and noticed that the new shell prompt introduced in https://github.com/thoughtbot/dotfiles/pull/239 doesn't work properly when running as root. Here's the output:

```
~ % sudo su
Password:
sh: git_prompt_info: command not found
%{[blue]%}%c%{%} %#
```

**Comment by geoffharcourt** [comment]
Keith correctly points out that `git_prompt_info` isn't defined for `sh` (it's also not defined for `bash` or any non-`zsh` shell), and that we have a problem with `PS1`, but this isssue doesn't have anything to do with `sudo`. You can get the same problem by starting `sh` or `bash`, etc. as yourself rather than the superuser.

Defining `git_prompt_info` shouldn't be hard (even if we just have a dummy shim that outputs nothing rather than an error), but I'm not sure if changing `PS1` in another shell will have consequences for later or already existing shells.
