### ISSUE TITLE
Maintaining a fork

### ISSUE THREAD

**Issue by blainesch** [thoughtbot/dotfiles#480]
So the problem exists when I try and pull in changes. The workflow I use at work for updating a branch would usually involve a rebase to avoid merge commits. This is problematic in this case, since a rebase would remove my gitconfig then the rebase would fail due to not having a gitconfig.

The best solution I have found is to squash my commits, which means I could potentially lose history I might end up reverting later. After squashing I simply `fetch thoughtbot` then `reset --hard thoughtbot/master` then `cherry-pick` my single commit on top. This seems like odd behavior that this works, since it still recreates the commit (asserting based on a new sha1) but doesn't complain like the rebase does.

The same problem exists when I want to create a pull request, since you obviously don't want my gitconfig, I usually end up re-cloning the repo to make the changes. I've not played around much with [git worktree](https://git-scm.com/docs/git-worktree) but that could be a solution.

* There must be a better way of handling this.
* It would be great if this repo provided a solution, either as a `bin` script, custom git command, or at least docs on one solution.

Having a recommended solution could improve contributions, and approachability/adoption of the repo.

**Comment by geoffharcourt** [comment]
@blainesch are you making local changes that are just for you? Are those things that could be handled using `.local` files and/or your own local dotfiles repo with `rcm`?

For example, in the gitconfig situation you referred to I'm making overrides in my personal `gitconfig.local` rather than editing the team-shared thoughtbot `gitconfig` here: https://github.com/geoffharcourt/dotfiles-local/blob/master/gitconfig.local

**Comment by blainesch** [comment]
@geoffharcourt that's correct, but those are committed to the repo so it can be shared across multiple computers (work/home). Is this not the expected use case?

**Comment by blainesch** [comment]
@geoffharcourt oh! I see, you are keeping those in a [separate repo](https://github.com/geoffharcourt/dotfiles-local)! I didn't realize the `dotfiles` supported that. After digging around it's been in place for [a while](https://github.com/thoughtbot/dotfiles/commit/9a2cb782b151428711921dd6693da4365ce8c9c1) now. Thanks for pointing it out!

**Comment by blainesch** [comment]
Actually [this](https://github.com/thoughtbot/dotfiles/commit/62a2b5eb8ff98fed9b9ca6a7254e16beef3a3f05) is a better representation of when it was implemented.

**Comment by gylaz** [comment]
I've seen two ways of keeping a fork/local repo. The one pointed out here, where only the `*.local` files are kept in the personal repo (and `rcup`ing both). The other, is to keep a private repo with a copy of the thoughtbot's dotfiles plus `*.local` and any personal changes (this is what I do). In that case, I merge upstream -- because rebase doesn't really make sense, since it would need to override the history on master. Merging is useful in this case.

**Comment by blainesch** [comment]
@gylaz under the second option, and the one you do, how do you make a pull request without including all of your `.local` changes? My guess is you'd make the commit on top of your local changes, create a new branch, reset hard on upstream/master, then cherry pick?

**Comment by gylaz** [comment]
I haven't had to do a PR from personal branch, since I can make branches and PRs directly from this directory. But I do see your point. I'm not sure, but I think I would do something similar to what you described.
