### ISSUE TITLE
post-up hook is bash specific and doesn't honor /usr/bin/env

### ISSUE THREAD

**Issue by wangbus** [thoughtbot/dotfiles#517]
It is hard coded to `/bin/bash`

This is literally the only thing keeping things from playing nicely in FreeBSD and systems where bash isn't installed by default.

I have a fix but I'd like to figure out the route:

If you use`/usr/bin/env` in the `post-up hook`, it'll still require /bin/bash to be installed. However this is literally the only file that needs it. Can someone figure out if this would work with a zsh shebang line? Make sure to use `/usr/bin/env zsh` because many systems install their shells in `/usr/local/bin` or `/usr/bin`

**Comment by geoffharcourt** [comment]
@wangbus I read this two weeks ago and still havent' figured out a solution. Just wanted to let you know I'm thinking about this.

**Comment by geoffharcourt** [comment]
cc: @thoughtbot/shell

**Comment by mike-burns** [comment]
Why are we mandating GNU Bash for that? Is it because of https://github.com/thoughtbot/dotfiles/blob/2fa36ccf9dab57597dc3296381474641a5cbd813/hooks/post-up#L24-L29 ?

What does that too/why is that there?

And, can we run that block conditional on the existence of `$BASH_SOURCE`?

(Hello, fellow BSD user! This obsession with `#!/bin/bash` is quite the thing, isn't it? I sometimes worry that I'll come back from vacation to find it across every shell script in the company ...)

**Comment by geoffharcourt** [comment]
The script changed from using sh to Bash in 16219a31db5ca1f8c766d3c6066399950ff7f2c3, which was where we tackled the dreaded (ongoing?) OSX/macOS zsh configuration change dance.

My shell-fu isn't super-strong, but I'm looking into what we can do.
