### ISSUE TITLE
Problems with UnPlug?

### ISSUE THREAD

**Issue by croaky** [thoughtbot/dotfiles#524]
Think I'm doing something wrong here:

```
dotfiles ale % v laptop.local
Error detected while processing function plug#end:
line   15:
E716: Key not present in Dictionary: syntastic
E15: Invalid expression: g:plugs[name]
Error detected while processing function plug#end[71]..<SNR>7_reorg_rtp:
line   13:
E716: Key not present in Dictionary: syntastic
E116: Invalid arguments for function s:rtp(g:plugs[v:val])
Error detected while processing /Users/croaky/.vimrc.local:
line   63:
E185: Cannot find color scheme 'github'
Press ENTER or type command to continue
```

The above happens when I add `UnPlug 'syntastic'` to the top of my `vimrc.bundles.local`. I can fix it by commenting it out:

https://github.com/croaky/dotfiles/compare/ale?expand=1

I'm guessing it's because I have my personal dotfiles listed first with https://github.com/thoughtbot/rcm

`DOTFILES_DIRS="$HOME/src/github.com/croaky/dotfiles $HOME/src/github.com/thoughtbot/dotfiles"`

If I list thoughtbot/dotfiles last, there's no way to use `UnPlug`, right?

**Comment by geoffharcourt** [comment]
I wonder if you could copy some of the stuff we did/do with `UnPlug` into your own dotfiles?

What's the use case for personals first, then tb?

**Comment by floesche** [comment]
Not sure if this is helpful, but I had the exact same error, but with my own dotfiles loaded after thoughtbot's. 

It turned out, the problem was having an old `plug.vim` from last year. Since I used `rcup` only to update my configuration (as opposed to rebuilding from scratch) `.vim/autoload/plug.vim` always existed and was therefore never updated through the `post-up` hook. A manual update to the [latest release vim-plug-0.9.1](https://github.com/junegunn/vim-plug/releases/latest) (and also to the current HEAD) solved the problem for me.

**Comment by croaky** [comment]
Closing for #532
