### ISSUE TITLE
Way to customize gitignore?

### ISSUE THREAD

**Issue by iancanderson** [thoughtbot/dotfiles#566]
Is there a way to add more entries to the gitignore using a `.local` override? I tried defining `gitignore.local` in my dotfile overrides repo, but that didn't seem to have an effect.

**Comment by geoffharcourt** [comment]
@iancanderson I've handled this by having my own file in `git_template/info/exclude` (same syntax as `gitignore`) in my dotfiles to add local ignores, but I don't know of a way to do this with a different file name.

**Comment by geoffharcourt** [comment]
I think we're constrained by the way the tool works.

**Comment by StevenXL** [comment]
I ended up adding a `gitignore.local` to my `dotfiles-local` repo. Then I added this line to `gitconfig.local`:

```
excludesfile = ~/.gitignore.local
```

This works because the `gitignore.local` is going to get symlinked to `~/.gitignore.local`. 

It's the only way I could figure out to get a working `gitignore.local` without touching the "parent" `dotfiles` repo.

**Comment by geoffharcourt** [comment]
@StevenXL this is clever!
