### ISSUE TITLE
Ale preventing backend code recompilation in Phoenix projects

### ISSUE THREAD

**Issue by sublimecoder** [thoughtbot/dotfiles#568]
Ale seems to be interfering with the recompilation process in phoenix applications. Not sure the exact issue but does anyone have a workaround, they are using?

**Comment by sublimecoder** [comment]
So after some digging I figured out the issue is related to ale running compilation on a file and messing with its metadata in the _build folder in some fashion. Turning off ale fixes it, or setting `MIX_ENV=edit vim` when opening which forces ale to compile to ./_build/edit instead of ./_build/dev So you have vim running in edit and phx.server running in dev.

As a work around I added these lines to my .aliases.local

```bash
alias vim='MIX_ENV=edit vim'
alias vi='MIX_ENV=edit vim'
alias v= 'MIX_ENV=edit vim'
```
or if you're using nvim like I am.
```bash
alias vim='MIX_ENV=edit nvim'
alias vi='MIX_ENV=edit nvim'
alias v= 'MIX_ENV=edit nvim'
```
Not sure if this is the best work around but it works for now.

**Comment by geoffharcourt** [comment]
Interesting... there are several thoughtbotters who are using ALE and working on Phoenix applications, so I'm surprised this hasn't come up before. 

cc: @thoughtbot/elixir

**Comment by sublimecoder** [comment]
Yeah that shocked me as well. It only effects backend code since views css and js are watched by node, and the auto reload for that works. But modifying a controller, model, or other pure elixir code part of the app won’t cause a recompile. If I use emacs or atom, the error goes away or if I unplug ALE. Issue solved, but I’d like to use ale and vim, and the above workaround I’m using feels flawed.

Was hoping some thoughtbotters knew the answer or if not then I could bring some attention to the issue Incase others are experiencing it.

**Comment by BlakeWilliams** [comment]
This has burned me in the past, but I don't think it was with ALE. According to the [ALE README](https://github.com/w0rp/ale) it has linters for Credo and Dogma but not one for compiler warnings which means `mix build` isn't getting hit. I believe `mix build` being called was the source of Phoenix applications not recompiling for me(some craziness with mtime I think).

I've been working on Dockerized Phoenix apps lately so that may also contribute to me not experiencing the issue as of late.

**Comment by sublimecoder** [comment]
There is a reference to this kind of issue over the last 2 years on the phoenix repo. https://github.com/phoenixframework/phoenix/issues/1165 but not sure its the same thing since I only recently have had issues with it myself. Also started a thread on the elixir forum https://elixirforum.com/t/vim-interfering-with-phoenix-recompile-after-saving/10039 in the hopes of finding a better solution than running vim in a different mix environment. Seems a little hacky to me, it at least works for now.

**Comment by dbernheisel** [comment]
l experience this as well, though haven't taken the time to debug it. I'm using neomake (credo and mix) and alchemist. I'm going to try out `MIX_ENV=test vim .` for a while and see if it fixes it for me. If this works, I suspect having a vimrc config telling neomake or ale to build in another folder will fix the issue.

Thanks @sublimecoder for those links.

**Comment by dbernheisel** [comment]
Ah! Ya, reading more comments about this, it seems `mix` is funky with timestamps. Neomake also ships with a maker `elixir`, https://github.com/neomake/neomake/blob/926ff19b50dd1e1d07b1a3c72517a3f51a5f44e1/autoload/neomake/makers/ft/elixir.vim#L36

I think I'll try this instead of opening VIM with `MIX_ENV=test` every time.

Sorry, I know my comments are more about Neomake than Ale, but we're getting there..

**Comment by geoffharcourt** [comment]
Is there any action left to take here? Let's reopen if so.

**Comment by exAspArk** [comment]
Seems like it was fixed https://github.com/w0rp/ale/pull/1266
