### ISSUE TITLE
How to remove the matched `"   ` on new line?

### ISSUE THREAD

**Issue by oliver-foggin** [thoughtbot/dotfiles#591]
In the .vimrc file it seems to add a feature to match the `"   ` of a comment line that you are on onto the next line.

So... if I'm on the line... `" Hello world, this is a comment!` and I press `o` I get a new line like `" ` but I would just like to have a blank new line.

I have tried going through each line of the `.vimrc` but I can't seem to find what is making it happen.

Please can you let me know.

Thanks

**Comment by thorncp** [comment]
That functionality is within Vim itself, not provided by the .vimrc here. More specifically, it's from the `formatoptions` setting. Taking a look at the docs, `:help formatoptions` it refers us to `fo-table`. Within `:help fo-table`, we see several options, including:

```
r	Automatically insert the current comment leader after hitting
	<Enter> in Insert mode.
o	Automatically insert the current comment leader after hitting 'o' or
	'O' in Normal mode.
```

Looking at the bundled [plugin file for VimScript](https://github.com/vim/vim/blob/f0b03c4e98f8a7184d8b4a5d702cbcd602426923/runtime/ftplugin/vim.vim#L22) (the filetype of .vimrc), we can see that both of these options are set

```
setlocal fo-=t fo+=croql
```

It sounds like you want to remove the `o` option: `set fo-=o`. Since this default config is in an ftplugin, it's reconfigured every time you open a buffer with that filetype. To effectively turn it off, I think you'll need to supply your own ftplugin with the options you want. If you're not familiar with that, you can follow the pattern in the [ftplugin](https://github.com/thoughtbot/dotfiles/tree/master/vim/ftplugin) directory, adding a new `vim.vim` file.

**Comment by oliver-foggin** [comment]
@thorncp but when I comment out the whole `.vimrc` file it stops doing it.

I tried commenting out the file in a sort of binary search but couldn't find the right line that causes it to start again.

What is the logic that determines what the comment leader is? Does it go by file type?

Thanks 😄

**Comment by oliver-foggin** [comment]
Ah, ok, that sort of makes sense. Thanks

Strange that when I comment every line of the .vimrc file it stops it from happening.

If I comment every line and then create a new line the new line does not start with `" `.

**Comment by thorncp** [comment]
I don't know off the top of my head, but if I had to guess, this line is probably the culprit:

https://github.com/thoughtbot/dotfiles/blob/21055dff633feea87bc9526efb5b2fcc04bc025e/vimrc#L18

**Comment by oliver-foggin** [comment]
Hi, thanks for the suggestions.

Neither of those seem to affect it.

I'll stay with it for now. Thanks
